[package]
name = "scp-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
sdl2 = "0.35.2"
glm = "0.2.3"
image = "0.24.7"
russimp = {version = "=2.0.5", features = ["prebuilt"]}